
const Discord = require('discord.js');
const Twana1 = new Discord.Client();
const Twana2 = new Discord.Client();
const Twana3 = new Discord.Client();
const Twana4 = new Discord.Client();
const Twana5 = new Discord.Client();
const Twana6 = new Discord.Client();
const Twana7 = new Discord.Client();
const Twana8 = new Discord.Client();
const Twana9 = new Discord.Client();
const Twana10 = new Discord.Client();
const Twana11 = new Discord.Client();
const Twana12 = new Discord.Client();
const Twana13 = new Discord.Client();
const Twana14 = new Discord.Client();
const Twana15 = new Discord.Client();
const Twana16 = new Discord.Client();
const Twana17 = new Discord.Client();
const Twana18 = new Discord.Client();
const Twana19 = new Discord.Client();
const Twana20 = new Discord.Client();
const Twana21 = new Discord.Client();
const Twana22 = new Discord.Client();
const Twana23 = new Discord.Client();
const Twana24 = new Discord.Client();
const Twana25 = new Discord.Client();
const Twana26 = new Discord.Client();
const Twana27 = new Discord.Client();
const Twana28 = new Discord.Client();
const Twana29 = new Discord.Client();
const Twana30 = new Discord.Client();
const Twana31 = new Discord.Client();
const Twana32 = new Discord.Client();
const Twana33 = new Discord.Client();
const Twana34 = new Discord.Client();
const Twana35 = new Discord.Client();
const Twana36 = new Discord.Client();
const Twana37 = new Discord.Client();
const Twana38 = new Discord.Client();
const Twana39 = new Discord.Client();
const Twana40 = new Discord.Client();
const Twana41 = new Discord.Client();
const Twana42 = new Discord.Client();
const Twana43 = new Discord.Client();
const Twana44 = new Discord.Client();
const Twana45 = new Discord.Client();
const Twana46 = new Discord.Client();
const Twana47 = new Discord.Client();
const Twana48 = new Discord.Client();
const Twana49 = new Discord.Client();
const Twana50 = new Discord.Client();
const Twana51 = new Discord.Client();
const Twana52 = new Discord.Client();
const Twana53 = new Discord.Client();
const Twana54 = new Discord.Client();
const Twana55 = new Discord.Client();
const Twana56 = new Discord.Client();
const Twana57 = new Discord.Client();
const Twana58 = new Discord.Client();
const Twana59 = new Discord.Client();
const Twana60 = new Discord.Client();
const Twana61 = new Discord.Client();
const Twana62 = new Discord.Client();
const Twana63 = new Discord.Client();
const Twana64 = new Discord.Client();
const Twana65 = new Discord.Client();
const Twana66 = new Discord.Client();
const Twana67 = new Discord.Client();
const Twana68 = new Discord.Client();
const Twana69 = new Discord.Client();
const Twana70 = new Discord.Client();
const Twana71 = new Discord.Client();
const Twana72 = new Discord.Client();
const Twana73 = new Discord.Client();
const Twana74 = new Discord.Client();
const Twana75 = new Discord.Client();
const Twana76 = new Discord.Client();
const Twana77 = new Discord.Client();
const Twana78 = new Discord.Client();
const Twana79 = new Discord.Client();
const Twana80 = new Discord.Client();
const Twana81 = new Discord.Client();
const Twana82 = new Discord.Client();
const Twana83 = new Discord.Client();
const Twana84 = new Discord.Client();
const Twana85 = new Discord.Client();
const Twana86 = new Discord.Client();
const Twana87 = new Discord.Client();
const Twana88 = new Discord.Client();
const Twana89 = new Discord.Client();
const Twana90 = new Discord.Client();
const Twana91 = new Discord.Client();
const Twana92 = new Discord.Client();
const Twana93 = new Discord.Client();
const Twana94 = new Discord.Client();
const Twana95 = new Discord.Client();
const Twana96 = new Discord.Client();
const Twana97 = new Discord.Client();
const Twana98 = new Discord.Client();
const Twana99 = new Discord.Client();
const Twana100= new Discord.Client();



Twana1.login("ODE1Mjc3MzQxODMwOTM4Njk0.YDqFSg.DL9lxsTi6ZSFUPDHBaRr6Eh2ih0");
Twana2.login("ODE1Mjc4NjI4MjgyODI2Nzc0.YDqGHA.QWrmkgFAaO0TvRByckIyL6vVf8w");
Twana3.login("ODE1Mjc5NDU1ODczNjYzMDE3.YDqG1w.4ou9H99FM1h9I8fAMOobs6dWmJU");
Twana4.login("ODE1MjgwMjQ4NzIyOTQ4MTA2.YDqHwA.oHcveQKShDxoGNkR7cxOeQAQW5c");
Twana5.login("ODE1MjgxMjE2Nzk0MDAxNDE4.YDqIUg.pP1OlIRAqk7NWPYSjFShy2fJpvw");
Twana6.login("ODE1MjgxODMzOTk3NjMxNDg5.YDqI5A.j6jQFCD7PAo5tfPjdea52FCBp6Y");
Twana7.login("ODE1MjgyNDQxNjEwMzMwMTYw.YDqJVQ.hdEJIRAiLVhZksY__khSeiEcIw4");
Twana8.login("ODE1MjgzMjUyNzA0ODM3NzAy.YDqKNQ.yhg2x5SiE_4aGsxEUqoYKxAEXF0");
Twana9.login("ODE1MjgzODU1NDgwOTc5NDU2.YDqKtA.LhNx3VVEaKoIxASWU-n0lxUI17I");
Twana10.login("ODE1Mjg0NDY0NTA2NTAzMTk5.YDqLjw.rSfpfr0v-0Qsa4Wjdhz_R9vHazs");
Twana11.login("ODE1Mjg1MzM3MDY3ODgwNDk5.YDqMEg.2A9E1x7wiBAYK6MzZ2RvfliWen0");
Twana12.login("ODE1Mjg1ODcyMjE1NzIwMDA2.YDqMiQ.p2OCbzWY5J2pChgC2X2rS0sL5W4");
Twana13.login("ODE1Mjg2MzU3ODMyMzY4MTU5.YDqNCA.9wPqP1WOhJsVx2HNux4xNpUho54");
Twana14.login("ODE1Mjg2OTE2OTcwODQwMDk0.YDqNjQ.V06LOKZwaP_tmUi6ggog4snui_c");
Twana15.login("ODE1Mjg3NDY5ODk2ODkyNDI3.YDqOFw.QVtDHqyF_hEpt3PaHbcowS0s8xU");
Twana16.login("ODE1Mjg4MDE3MzY2OTQxNjk3.YDqOlw.k522SoVUEWFCt8GapO7tzVGjWyA");
Twana17.login("ODE1Mjg4NTYwNjU5MjAyMDQ4.YDqPDw.QGDgi1tZv_5VIiTIKIuV_ZD09bY");
Twana18.login("ODE1Mjg5MDc0MjM0ODE4NTcw.YDqPjQ.h47b_wYmmCKj8jS1jF3bXzqNCRI");
Twana19.login("ODE1Mjg5NjE3MTU0MTc5MTM0.YDqQRQ._lJDG1diCDDBatw-6KvkgTZK3Xw");
Twana20.login("ODE1MjkwMzY0NjkyNTI5MTgy.YDqQvg.0NevlV8B1rL1Sb4muECByuUq4BA");
Twana21.login("ODE1MjkwODYyNjM5OTA2ODE4.YDqSGg.eWfNjHGi5k_mFsTRQ1M1mZvD1F8");
Twana22.login("ODE1MjkyMzQ1MDMzNDI0OTM3.YDqSqA.sBVH-NLqBKwUZjCXNbcCTkV6ijk");
Twana23.login("ODE1MDE5ODQ3OTc2MzUzODAy.YDmU-Q.i4-mdqsPxGwjFzfEN-fjrZvWWyY");
Twana24.login("ODE1MDIwNDY0MTIwMDA0NjU4.YDmVww.MKUXkdDVExMq9XqwXauMwtRQDYE");
Twana25.login("ODE1MDIxMTI2MDczMDU3Mjgw.YDmWEQ.ypOjfZ4Zd_WfvRqw0DV8h8osZtI");
Twana26.login("ODE1MDIyNDUzNjA4Mjg0MTgw.YDmXRQ.o9985RSdFmhoEDH0DQstBdB768k");
Twana27.login("ODE1MDE0Mjg4OTEzMzM0Mjgy.YDoHjA.a1KBpJdv3VTkRklPcTQ7yc4B9eY");
Twana28.login("ODE1MTQzNDE4MTc4OTYxNDA5.YDoIFg.h9xx2v_MUwbkStPf8KY7Xf6oToA");
Twana29.login("ODE1MTQ0MDY2ODMyMDA3MjE4.YDoIgQ.gilLa4Ivzs9tglfGylmt2O0zKwo");
Twana30.login("ODE1MTQ0NTE0NjE2MTY0Mzky.YDoJAQ.H4zKM2uCqt9oloib0wAZYh9tNI0");
Twana31.login("ODE1MTQ1MDQwMzQ2NzQyNzk1.YDoJiw.IMJT4hT5E9l0hLuB6ewWNjGL4Gc");
Twana32.login("ODE1MTQ1NTM4MDA1MzY4ODQz.YDoJ_Q.5XSLaPbidNrPTK-n1GqsrsP1gPU");
Twana33.login("ODE1MTQ2MDk3MzAzMDkzMjU4.YDoKmw.AgJwKRvIMuwkyqG4AQVfrhixWYk");
Twana34.login("ODE1MDIyOTEzMTA2MjE0OTIy.YDp92A.nI6iN_NpZr0IqBUi1ObYEezOwrM");
Twana35.login("ODE1MjcwMDI5MDA0MTExOTUy.YDp98A.BcfY2CgEPuZOX-oMY-88k9ROBaY");
Twana36.login("ODE1MjcwMzkwNDE4NzY3OTAz.YDp-bg._Wv85uFLz_D-bg5MioHJ1bY-TL8");
Twana37.login("ODE1MjcxMDYzNDA2NTEwMTEw.YDp-4w.gT31EOcYH_pxomNdz4h0_GtIwlo");
Twana38.login("ODE1MjcxNDc4MjM2Njc2MTM2.YDp_QA.M1CB-WUnEFzb7pdZZK94qPH2eco");
Twana39.login("ODE1MjcxOTU5ODUxMDQwNzc4.YDp_6A.S4wwx7nT7wUoVGcnl6FnMPF6M-A");
Twana40.login("ODE1MjcyNjQ0MTQwMjA0MDcz.YDqAXQ.DMi8PdUrNLjfWuUpjdjhfGwXN_k");
Twana41.login("ODE1MjczMTIyMDM0ODc2NDE2.YDqA3A.ki9ZD-QB3R3P7D9HjOa58hRa0cY");
Twana42.login("ODE1MjczNjI3NDk0MTIxNDky.YDqBaQ.HsLyDAmGJGzmWvVGPyr6y-KF8c0");
Twana43.login("ODE1Mjc0MjYxMjU3MTI1OTQ4.YDqB5g.dPNN70RYkiJncVQRuOD_f3hNNGM");
Twana44.login("ODE1Mjc0NzczOTAyOTE3NzEy.YDqClw.rsMC-zRAJNJvq79izq7rN-hN7mI");
Twana45.login("ODE1Mjc1NDk1NTY1Njg4ODMz.YDqDOQ.i3_6aowjxKntQadOTr_82n2CF9A");
Twana46.login("");
Twana47.login("");
Twana48.login("");
Twana49.login("");
Twana50.login("");
Twana51.login("");
Twana52.login("");
Twana53.login("");
Twana54.login("");
Twana55.login("");
Twana56.login("");
Twana57.login("");
Twana58.login("");
Twana59.login("");
Twana60.login("");
Twana61.login("");
Twana62.login("");
Twana63.login("");
Twana64.login("");
Twana65.login("");
Twana66.login("");
Twana67.login("");
Twana68.login("");
Twana69.login("");
Twana70.login("");
Twana71.login("");
Twana72.login("");
Twana73.login("");
Twana74.login("");
Twana75.login("");
Twana76.login("");
Twana77.login("");
Twana78.login("");
Twana79.login("");
Twana80.login("");
Twana81.login("");
Twana82.login("");
Twana83.login("");
Twana84.login("");
Twana85.login("");
Twana86.login("");
Twana87.login("");
Twana88.login("");
Twana89.login("");
Twana90.login("");
Twana91.login("");
Twana92.login("");
Twana94.login("");
Twana95.login("");
Twana96.login("");
Twana97.login("");
Twana98.login("");
Twana99.login("");
Twana100.login("");









